### ISSUE TITLE
Different paths on project references generate different nodes

### ISSUE THREAD

**Issue by GrizzlyEnglish** [mducharm/PlotNet#1]
If I have a project reference by two other projects with a different path they are added separately

**Comment by mducharm** [comment]
For example, if you have these relative references in a given project like this:

```xml
  <ItemGroup>
    <ProjectReference Include="..\ApplicationCore\ApplicationCore.csproj" />
    <ProjectReference Include="..\BlazorAdmin\BlazorAdmin.csproj" />
    <ProjectReference Include="..\BlazorShared\BlazorShared.csproj" />
    <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
  </ItemGroup>
```
It currently creates nodes labeled `..\Infrastructure\Infrastructure.csproj` instead of associating it with the existing node for that project.
